# Generated by Django 2.1.5 on 2020-04-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
    ]
